min_height = 3
max_height = 26
min_width = 3
max_width = 26
allowed_items = ['/', '\\', '|', '-', '#', 'o']
allowed_directions = ['>', '<', 'v', '^']
phase_one_duration = 15000
second_display_duration = 5000
images_folder = 'img/'
min_random_height = 3
max_random_height = 5
min_random_width = 3
max_random_width = 5
min_random_items = 4
max_random_items = 6
game_name = 'Through the looking glass'